#1-repo-conf
Monitoring-Mtl/Bixi-Api pull request #3
Opened 2024-02-04 06:59 UTC by k-allagbe

## Description

Setting up Repository Configuration.

## Related Issue

Closes #1

## Changes Made
- [x] issue template
- [x] workflows
- [x] pr template

2024-02-07 17:17 UTC, CharlesBourgeois requested changes
Il manque le template pour la documentation, pour suivre la standardisation effectué sur les autres projets.

Je vais m'occuper dans un prochain issue de configurer les pipelines.

Sinon all good pour la config général!

2024-02-07 20:28 UTC, AlexandreEngloner reviewed
Discussion que l'équipe a eu au sujet de ce nouveau repository:

- **Pourquoi ne pas simplement utiliser le repo du Serverless-API ?**
1. Séparer par micro-services: Pas besoin de redéployer à chaque fois les APIs de la STM.
2. Indépendance des failles entre les services de Bixi et de STM
3. Facilite le développement en parallèle pour les sessions futures s'ils sont plus nombreux.
4. Permet d'analyser d'autres voies que le Node.js pour nos APIs

- **Pourquoi ne pas garder nos langages d'API uniforme en gardant Node.js au lieu de python ?**
1. Matériel fourni par l'AWS Immersion Day est en python seulement.
2. L'équipe est plus familière avec le Python que le Node.js.
3. Démarrage à froid: Node.js garde le dessus généralement, mais Python peut avoir l'avantage selon le contexte (Voir lien plus bas)
4. Typescript est plus performant que Python, mais nos tâches de Bixi ne sont pas très CPU intensive.

[python-vs-nodejs-benchmark](https://antonputra.com/python/python-vs-nodejs-benchmark/#create-nodejs-lambda-function)
[aws-lambda-battle-2021-performance-comparison-for-all-languages](https://filia-aleks.medium.com/aws-lambda-battle-2021-performance-comparison-for-all-languages-c1b441005fd1)
[AWS Lambda performance](https://www.simform.com/blog/aws-lambda-performance/)
[aws-lambda-runtime-performance](https://www.linkedin.com/pulse/aws-lambda-runtime-performance-nigel-slack-smith)

2024-02-08 07:12 UTC, k-allagbe commented
> Il manque le template pour la documentation, pour suivre la standardisation effectué sur les autres projets.
> 
> Je vais m'occuper dans un prochain issue de configurer les pipelines.
> 
> Sinon all good pour la config général!

C'est fait. Je crois qu'il est aussi possible de centraliser les templates et autres en avec un repo `.github`. Je ne suis pas certain de comment ça marche exactement mais ça pourrait éviter du travail répété.

2024-02-15 23:25 UTC, CharlesBourgeois approved these changes
nice work!

2024-02-16 02:31 UTC, merged